--- #https://certbot.eff.org/instructions?ws=other&os=ubuntuother

  - name: "Create required directory /etc/letsencrypt"
    file:
      path: "/etc/letsencrypt"
      state: directory
      owner: vault
      group: vault
      mode: u=rwx,g=x,o=x

  - name: "Create required directories in /etc/letsencrypt"
    file:
      path: "/etc/letsencrypt/{{ item }}"
      state: directory
      owner: vault
      group: vault
      mode: u=rwx,g=x,o=x
    with_items:
    - account
    - certs
    - csrs
    - keys
    - archive

  - name: ensure snapd
    package:
      name: snap

  - name: ensure nginx
    package:
      name: nginx
  
  - name: ensure certbot
    community.general.snap:
      name: certbot
      classic: true

  - name: link snapbot
    file:
      state: link
      src: /snap/bin/certbot
      dest: /usr/bin/certbot

  - name: Register certbot
    shell: |
      certbot -n register --agree-tos --email james.sandford@blinkbyte.co.uk
      touch /etc/letsencrypt/.registered
    args:
      creates: /etc/letsencrypt/.registered

  - name: Setup cronjob for renewal
    cron:
      name: certbot-renewal
      job: "/bin/bash -lc 'certbot -q renew'"
      minute: "0"
      hour: "14"

  - name: 'Get certificate'
    command: 'certbot -n --nginx certonly -d {{ vault_api_addr }}'
    args:
      creates: '/etc/letsencrypt/live/{{ vault_api_addr }}'

  - name: ensure perms for dir
    file: 
      name: "{{ item }}"
      owner: vault
      group: vault
      state: directory
    with_items:
      - /etc/letsencrypt/live/

  - name: ensure perms for files
    file: 
      name: "{{ item }}"
      owner: vault
      group: vault
    with_items:
      - /etc/letsencrypt/live/{{ vault_api_addr }}/cert.pem
      - /etc/letsencrypt/live/{{ vault_api_addr }}/privkey.pem